USE [master]
GO
/****** Object:  Database [suvoda]    Script Date: 10/26/2016 4:31:29 PM ******/
CREATE DATABASE [suvoda]
 
GO
ALTER DATABASE [suvoda] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [suvoda].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [suvoda] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [suvoda] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [suvoda] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [suvoda] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [suvoda] SET ARITHABORT OFF 
GO
ALTER DATABASE [suvoda] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [suvoda] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [suvoda] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [suvoda] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [suvoda] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [suvoda] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [suvoda] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [suvoda] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [suvoda] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [suvoda] SET  DISABLE_BROKER 
GO
ALTER DATABASE [suvoda] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [suvoda] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [suvoda] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [suvoda] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [suvoda] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [suvoda] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [suvoda] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [suvoda] SET RECOVERY FULL 
GO
ALTER DATABASE [suvoda] SET  MULTI_USER 
GO
ALTER DATABASE [suvoda] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [suvoda] SET DB_CHAINING OFF 
GO
ALTER DATABASE [suvoda] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [suvoda] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [suvoda] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'suvoda', N'ON'
GO
ALTER DATABASE [suvoda] SET QUERY_STORE = OFF
GO
USE [suvoda]
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [suvoda]
GO
/****** Object:  Table [dbo].[Country]    Script Date: 10/26/2016 4:31:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Country](
	[CountryId] [int] IDENTITY(1,1) NOT NULL,
	[CountryName] [nchar](50) NOT NULL,
 CONSTRAINT [PK_Country] PRIMARY KEY CLUSTERED 
(
	[CountryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Depot]    Script Date: 10/26/2016 4:31:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Depot](
	[DepotId] [int] IDENTITY(1,1) NOT NULL,
	[DepotName] [nchar](50) NOT NULL,
	[DepotLocation] [int] NOT NULL,
 CONSTRAINT [PK_Depot] PRIMARY KEY CLUSTERED 
(
	[DepotId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[DepotDestinations]    Script Date: 10/26/2016 4:31:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DepotDestinations](
	[DepotId] [int] NOT NULL,
	[CountryId] [int] NOT NULL,
	[Id] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_DepotDestinations] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[DrugType]    Script Date: 10/26/2016 4:31:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DrugType](
	[DrugTypeId] [int] IDENTITY(1,1) NOT NULL,
	[DrugTypeName] [nchar](250) NOT NULL,
	[Weight] [numeric](16, 2) NOT NULL,
 CONSTRAINT [PK_DrugType] PRIMARY KEY CLUSTERED 
(
	[DrugTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[DrugUnit]    Script Date: 10/26/2016 4:31:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DrugUnit](
	[DrugUnitId] [int] IDENTITY(1,1) NOT NULL,
	[PickNumber] [int] NOT NULL,
	[DrugTypeId] [int] NOT NULL,
	[DepotId] [int] NULL,
 CONSTRAINT [PK_DrugUnit] PRIMARY KEY CLUSTERED 
(
	[DrugUnitId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[Depot]  WITH CHECK ADD  CONSTRAINT [FK_Depot_Country] FOREIGN KEY([DepotLocation])
REFERENCES [dbo].[Country] ([CountryId])
GO
ALTER TABLE [dbo].[Depot] CHECK CONSTRAINT [FK_Depot_Country]
GO
ALTER TABLE [dbo].[DepotDestinations]  WITH CHECK ADD  CONSTRAINT [FK_DepotDestinations_Country] FOREIGN KEY([CountryId])
REFERENCES [dbo].[Country] ([CountryId])
GO
ALTER TABLE [dbo].[DepotDestinations] CHECK CONSTRAINT [FK_DepotDestinations_Country]
GO
ALTER TABLE [dbo].[DepotDestinations]  WITH CHECK ADD  CONSTRAINT [FK_DepotDestinations_Depot] FOREIGN KEY([DepotId])
REFERENCES [dbo].[Depot] ([DepotId])
GO
ALTER TABLE [dbo].[DepotDestinations] CHECK CONSTRAINT [FK_DepotDestinations_Depot]
GO
ALTER TABLE [dbo].[DrugUnit]  WITH CHECK ADD  CONSTRAINT [FK_DrugUnit_Depot] FOREIGN KEY([DepotId])
REFERENCES [dbo].[Depot] ([DepotId])
GO
ALTER TABLE [dbo].[DrugUnit] CHECK CONSTRAINT [FK_DrugUnit_Depot]
GO
ALTER TABLE [dbo].[DrugUnit]  WITH CHECK ADD  CONSTRAINT [FK_DrugUnit_DrugType] FOREIGN KEY([DrugTypeId])
REFERENCES [dbo].[DrugType] ([DrugTypeId])
GO
ALTER TABLE [dbo].[DrugUnit] CHECK CONSTRAINT [FK_DrugUnit_DrugType]
GO
USE [master]
GO
ALTER DATABASE [suvoda] SET  READ_WRITE 
GO
